---
kind: pipeline
type: kubernetes
name: lint

node_selector:
  drone: "true"

steps:
  - name: lint
    image: node:10
    commands:
      - make install
      - make lint

---
kind: pipeline
type: kubernetes
name: build

node_selector:
  drone: "true"

steps:
  - name: build
    pull: always
    image: banzaicloud/drone-kaniko:0.5.1
    when:
      branch:
        exclude:
          - master

---
kind: pipeline
type: kubernetes
name: publish

depends_on:
  - lint
  - build

node_selector:
  drone: "true"

steps:
  - name: publish
    pull: always
    image: banzaicloud/drone-kaniko:0.5.1
    environment:
      HUGIN_MAPBOX_ACCESS_TOKEN:
        from_secret: hugin_mapbox_access_token
      HUGIN_ROLLBAR_ACCESS_TOKEN:
        from_secret: hugin_rollbar_access_token
      HUGIN_SENTRY_DSN:
        from_secret: hugin_sentry_dsn
    settings:
      build_args_from_env:
        - HUGIN_MAPBOX_ACCESS_TOKEN
        - HUGIN_ROLLBAR_ACCESS_TOKEN
        - HUGIN_SENTRY_DSN
      repo: kradalby/hugin
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

---
kind: pipeline
type: kubernetes
name: deploy

depends_on:
  - publish

node_selector:
  drone: "true"

steps:
  - name: deploy
    pull: always
    image: kradalby/drone-kubectl
    environment:
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
      APP: hugin
    commands:
      - kubectl -n $APP set image deployment/$APP $APP=kradalby/$APP:${DRONE_COMMIT_SHA:0:8} --record
      - kubectl -n $APP rollout status deployment $APP
    when:
      branch:
        - master
      event:
        - push

---
kind: pipeline
type: kubernetes
name: deploy-demo

depends_on:
  - publish

node_selector:
  drone: "true"

steps:
  - name: deploy
    pull: always
    image: kradalby/drone-kubectl
    environment:
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
      APP: hugindemo
    commands:
      - kubectl -n $APP set image deployment/$APP common=kradalby/$APP:${DRONE_COMMIT_SHA:0:8} --record
      - kubectl -n $APP rollout status deployment $APP
    when:
      branch:
        - master
      event:
        - push

---
kind: pipeline
type: kubernetes
name: notify

depends_on:
  - deploy
  - deploy-demo

node_selector:
  drone: "true"

steps:
  - name: notify
    pull: always
    image: drillster/drone-email
    settings:
      from: drone@drone.fap.no
      host: smtp.fap.no
      port: 25
      recipients:
        - kradalby@kradalby.no
      skip_verify: true
    when:
      status:
        - changed
        - failure

---
kind: secret
name: docker_username
get:
  path: docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker
  name: password
