pipeline:
  build:
    image: plugins/docker
    repo: kradalby/hugin
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    environment:
        - MAPBOX_ACCESS_TOKEN: $$mapbox_token 
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: hugin-deployment
    repo: kradalby/hugin
    container: hugin-container
    namespace: hugin
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
