pipeline:
  lint:
    image: node:10
    commands:
        - make install
        - make lint
  build:
    image: plugins/docker
    repo: kradalby/hugin
    # auto_tag: true
    secrets:
        - docker_username
        - docker_password
        - hugin_mapbox_access_token
        - hugin_sentry_dsn
        - hugin_rollbar_access_token
    build_args_from_env:
        - HUGIN_MAPBOX_ACCESS_TOKEN
        - HUGIN_SENTRY_DSN
        - HUGIN_ROLLBAR_ACCESS_TOKEN
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: hugin-deployment
    repo: kradalby/hugin
    container: hugin-container
    namespace: hugin
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  deploy-demo:
    image: quay.io/honestbee/drone-kubernetes
    deployment: hugindemo-deployment
    repo: kradalby/hugin
    container: hugindemo-container
    namespace: hugin
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
