{{ if .Values.configmap -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hugin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hugin.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ with .Values.configmap -}}
data: {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
