name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check

      - name: Lint
        run: nix develop --command -- prek run --all-files --show-diff-on-failure

      - name: Build
        run: nix build .#hugin
