name: Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: cachix/install-nix-action@v22

      - name: Install dependencies
        run: nix develop --command -- yarn

      - name: Build
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          # Allow the build to retry, elm has an issue were
          # it fails to build because "constraints are too wide"
          # but it isnt correct.
          max_attempts: 3
          retry_on: error
          command: nix develop --command -- make build

      # - name: Deploy to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
      #     cname: beta.aspargesgaarden.no
